### ISSUE TITLE
support reading stdin for file arguments

### ISSUE THREAD

**Issue by anandthakker** [Turfjs/turf-cli#6]
How about allowing `-` wherever a file argument is expected, and reading from stdin in that case?

**Comment by morganherlocker** [comment]
This will get tricky for commands with multiple geojson args (lots of turf). I've played around with multiple streams using xargs, but never made it to a satisfactory interface.

**Comment by anandthakker** [comment]
@morganherlocker True, but as a simple first step, couldn't we just limit to one `-` argument?

**Comment by anandthakker** [comment]
Ping @morganherlocker @tmcw any objections to allowing at most one file argument to be `-` for stdin?

**Comment by tmcw** [comment]
I'd be down for allowing an - argument for the single-stream case.
